name: balanced_workout
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dotted_box: ^0.0.3
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  wheel_picker: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
